# Generated by Django 3.2.6 on 2021-08-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jugador',
            options={'verbose_name': 'Jugador', 'verbose_name_plural': 'Jugadores'},
        ),
        migrations.AddField(
            model_name='jugador',
            name='puntaje',
            field=models.IntegerField(default=0),
        ),
    ]
